### ISSUE TITLE
Bounty does not pay out when Better Combat Rebirth mod is installed

### ISSUE THREAD

**Issue by azokthedefiler1** [rm2023/RBounty#1]
I tried adding this plugin to my server, but it doesn't pay out if you have the Better Combat Rebirth mod installed. It doesn't seem to pick up that the bounty'd player was killed. Everything else works as expected. Simply removing the Better Combat Rebirth mod makes it work as expected also.

You can duplicate the issue with the following setup:

Sponge: spongeforge-1.12.2-2838-7.2.3.jar
Forge: forge-1.12.2-14.23.5.2838-universal.jar
Mods: BetterCombat-1.12.2-1.5.6.jar

Plugins:
LuckPerms-Sponge-5.1.73.jar
Nucleus-1.14.6-S7.1-MC1.12.2-plugin.jar
TotalEconomy-1.8.1.jar
RBounty-1.0.1.jar

Better Combat Rebirth download: https://www.curseforge.com/minecraft/mc-mods/better-combat-rebirth
Better Combat Rebirth github: https://github.com/SanAndreasP/BetterCombatRebirth

**Comment by Robit** [comment]
Hey there. I don't plan to maintain this plugin anymore. You may be interested in compiling one of the forks to see if your issue persists there.
